php_packages:
  - unzip
  - curl
  - wget
  - php7.4-fpm
  - php7.4-pgsql
  - php7.4-gd
  - php7.4-mbstring
  - php7.4-curl
  - php7.4-intl
  - php7.4-zip
  - php7.4-xml
  - php7.4-json
  - php7.4-opcache
  - php7.4-xdebug
  - php-memcached
  - imagemagick

php_fpm_service: php7.4-fpm

php_composer_version: 1.10.13

php_fpm_pools_path: /etc/php/7.4/fpm/pool.d

php_fpm_pools: []
#  - name: app
#    template: php-fpm-pool.conf.j2
#    socket: /var/run/php-fpm.app.sock
#    user: deploy
#    user_group: www-data
