---
roles:

  - name: cloudteam.init
    src: git@git.cloud-team.ru:ansible-roles/init.git
    scm: git
    version: 1.0.12

  - name: cloudteam.postgresql
    src: git@git.cloud-team.ru:ansible-roles/postgresql.git
    scm: git
    version: 2.0.8
