---
- name: PHP application playbook
  hosts: all
  become: yes

  roles:
    - local.init
    - local.postgresql
    - local.php
    - local.app
    - local.nginx # Nginx needs application paths to add vhost
