init_locale: en_US.UTF-8
init_timezone: Europe/Moscow
init_ssh_allowed_groups:
  - sshers
  - vagrant
init_ssh_config:
  - { name: 'PasswordAuthentication', value: 'no' }
  - { name: 'PermitRootLogin', value: 'no' }
init_users:
  - name: deploy
    group: www-data
    groups:
      - sshers
    home: '/home/deploy'
    is_sudoer: yes
    known_hosts:
      - github.com
    private_key: ../inventories/vagrant/files/ssh/deploy_private_key
    authorized_keys:
      - ../inventories/vagrant/files/ssh/deploy_public_key.pub
init_open_ports:
  - '22'
  - '80'
  - '443'
  - '5432'

postgresql_version: 12
postgresql_password: secret
postgresql_databases:
  - name: yii2
    owner_name: yii2
    owner_password: 'yii2'
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

memcached_config:
  - '-l 127.0.0.1' # Bind to localhost only
  - '-U 0'         # Disable UDP protocol
  - '-m 64'        # Memory limit

php_packages:
  - unzip
  - curl
  - wget
  - php7.4-fpm
  - php7.4-pgsql
  - php7.4-gd
  - php7.4-mbstring
  - php7.4-curl
  - php7.4-intl
  - php7.4-zip
  - php7.4-xml
  - php7.4-json
  - php7.4-opcache
  - php7.4-xdebug
  - php-memcached
  - imagemagick
php_fpm_service: php7.4-fpm
php_composer_version: 1.10.13
php_fpm_pools_path: /etc/php/7.4/fpm/pool.d
php_fpm_pools:
  - name: app
    template: ../inventories/vagrant/files/php/php-fpm-pool.conf.j2
    socket: /var/run/php-fpm.app.sock
    user: deploy
    user_group: www-data
    locale: en_US.UTF-8

nginx_vhosts_path: /etc/nginx/sites-enabled
nginx_vhosts:
  - name: app
    template: ../inventories/vagrant/files/nginx/nginx-vhost.conf.j2
    server_name: '_'
    root: /home/deploy/app/web
    index_file: index.php
    access_log: /home/deploy/log/app-access.log
    error_log: /home/deploy/log/app-error.log
    fastcgi_index: index.php
    fastcgi_pass: 'unix:/var/run/php-fpm.app.sock'

apps:
  - name: app
    user: deploy
    user_group: www-data
    path: /home/deploy/app
    extra_directories:
      - /home/deploy/log
      - /home/deploy/.composer
    composer_github_auth_token: 'dbd6c5966b80f1379ad6c341fef220b8206ae985'
    composer_global_requirements: []
    composer_no_dev: no
    git_repo: 'ssh://git@github.com/kiaplayer/ansible-php-app.git'
    git_branch: master
    config_files:
      - src: ../inventories/vagrant/files/app/local.php
        dest: /home/deploy/app/config/local.php
    extra_commands:
      - command: php yii migrate --interactive=0
        chdir: /home/deploy/app
