init_locale: en_US.UTF-8
init_timezone: Europe/Moscow

init_ssh_allowed_groups:
  - sshers
  - vagrant
init_ssh_config:
  - { name: 'PasswordAuthentication', value: 'no' }
  - { name: 'PermitRootLogin', value: 'no' }
init_users:
  - name: deploy
    group: www-data
    groups:
      - sshers
    home: '/home/deploy'
    is_sudoer: yes
    known_hosts:
      - github.com
      - git.cloud-team.ru
    private_key: files/ssh/deploy_private_key
    authorized_keys:
      - files/ssh/deploy_public_key.pub

postgresql_version: 12
postgresql_password: secret
postgresql_databases:
  - name: yii2
    owner_name: yii2
    owner_password: 'yii2'
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

deploy_user: deploy
deploy_user_group: www-data
deploy_home: '/home/{{ deploy_user }}'
deploy_app_dir: '{{ deploy_home }}/www'
deploy_log_dir: '{{ deploy_home }}/log'
deploy_nginx_root: '{{ deploy_home }}/web'
deploy_nginx_access_log: '{{ deploy_log_dir }}/access.log'
deploy_nginx_error_log: '{{ deploy_log_dir }}/error.log'
deploy_php_fpm_socket: /var/run/php-fpm.app.sock
deploy_git_repo: 'ssh://git@github.com/kiaplayer/ansible-php-app.git'
deploy_git_branch: 'master'
deploy_composer_version: 1.10.13
deploy_composer_no_dev: no
deploy_composer_github_auth_token: 'dbd6c5966b80f1379ad6c341fef220b8206ae985'
deploy_composer_global_requirements: []
deploy_app_configs:
  - { src: 'files/app_config.php', dest: '{{ deploy_app_dir }}/config/local.php' }
